In [4]:
import pandas as pd
import numpy as np


btradron = pd.read_csv("/home/mihnearad/Development/BankingInfo-Parse-Script/.data/BTRADRON.csv", skiprows=16)

btradron["Currency"] = "RON"

btradeur = pd.read_csv("/home/mihnearad/Development/BankingInfo-Parse-Script/.data/BTRADEUR.csv", skiprows=16)

btradeur["Currency"] = "EUR"


df = pd.concat([btradron, btradeur], ignore_index=True)

df.head()

,Data tranzactie,Data valuta,Descriere,Referinta tranzactiei,Debit,Credit,Sold contabil,Currency
0,2024-08-08,2024-08-08,Plata la POS non-BT cu card VISA;EPOS 05/08/20...,000NVPO242214qI3,-49.99,NaN,114.31,RON
1,2024-08-02,2024-08-02,Plata la POS non-BT cu card VISA;EPOS 30/07/20...,000NVPO242154Boq,"-1,043.83",NaN,164.30,RON
2,2024-08-01,2024-08-01,Pachet IZI;Nelimitat in reteaua BT;REF: E41IZ5...,E41IZ56241800002,-29.00,NaN,"1,208.13",RON
3,2024-07-31,2024-07-31,Plata la POS non-BT cu card VISA;EPOS 28/07/20...,000NVPO242134gxY,-36.99,NaN,"1,237.13",RON
4,2024-07-22,2024-07-22,Plata OP inter - canal electronic;/ROC/./RFB/2...,E41ZEXA2420400GK,"-1,301.00",NaN,535.52,RON

In [5]:
df = df.drop(
    ["Referinta tranzactiei", "Credit", "Sold contabil", "Data valuta"], axis=1
)

df.head()

,Data tranzactie,Descriere,Debit,Currency
0,2024-08-08,Plata la POS non-BT cu card VISA;EPOS 05/08/20...,-49.99,RON
1,2024-08-02,Plata la POS non-BT cu card VISA;EPOS 30/07/20...,"-1,043.83",RON
2,2024-08-01,Pachet IZI;Nelimitat in reteaua BT;REF: E41IZ5...,-29.00,RON
3,2024-07-31,Plata la POS non-BT cu card VISA;EPOS 28/07/20...,-36.99,RON
4,2024-07-22,Plata OP inter - canal electronic;/ROC/./RFB/2...,"-1,301.00",RON

In [6]:
df["Payment Date"] = df["Descriere"].str.extract(r"(POS\s(\d{2}\/\d{2}\/\d{4}))")[1]
regex_pattern = r"Schimb valutar|LT383250069969855031|Comision"

mask = ~df["Descriere"].str.contains(regex_pattern)


filtered_df = df.loc[mask].copy()


date_formats = ["%d/%m/%Y", "%Y-%m-%d", "%d-%m-%Y"]  # Add all expected formats
for fmt in date_formats:
    filtered_df["Payment Date"] = pd.to_datetime(
        filtered_df["Payment Date"], format=fmt, errors="coerce"
    )


filtered_df["Data tranzactie"] = pd.to_datetime(df["Data tranzactie"], errors="coerce")

# Formatting dates to 'day-month-year'
filtered_df["Payment Date"] = filtered_df["Payment Date"].dt.strftime("%d-%m-%Y")
filtered_df["Data tranzactie"] = filtered_df["Data tranzactie"].dt.strftime("%d-%m-%Y")


filtered_df["Payment Date"] = filtered_df["Payment Date"].fillna(
    filtered_df["Data tranzactie"]
)


filtered_df.head()

,Data tranzactie,Descriere,Debit,Currency,Payment Date
0,08-08-2024,Plata la POS non-BT cu card VISA;EPOS 05/08/20...,-49.99,RON,05-08-2024
1,02-08-2024,Plata la POS non-BT cu card VISA;EPOS 30/07/20...,"-1,043.83",RON,30-07-2024
2,01-08-2024,Pachet IZI;Nelimitat in reteaua BT;REF: E41IZ5...,-29.00,RON,01-08-2024
3,31-07-2024,Plata la POS non-BT cu card VISA;EPOS 28/07/20...,-36.99,RON,28-07-2024
4,22-07-2024,Plata OP inter - canal electronic;/ROC/./RFB/2...,"-1,301.00",RON,22-07-2024

In [7]:
filtered_df["Merchant"] = filtered_df["Descriere"].str.extract(
    r"TID:\s*(?:[^\s]{2,8}\s+)?(\w+)"
)
filtered_df["Merchant"] = filtered_df["Merchant"].fillna(
    df["Descriere"].str.split(";").str[3]
)

filtered_df.head()

,Data tranzactie,Descriere,Debit,Currency,Payment Date,Merchant
0,08-08-2024,Plata la POS non-BT cu card VISA;EPOS 05/08/20...,-49.99,RON,05-08-2024,APPLE
1,02-08-2024,Plata la POS non-BT cu card VISA;EPOS 30/07/20...,"-1,043.83",RON,30-07-2024,PPC
2,01-08-2024,Pachet IZI;Nelimitat in reteaua BT;REF: E41IZ5...,-29.00,RON,01-08-2024,NaN
3,31-07-2024,Plata la POS non-BT cu card VISA;EPOS 28/07/20...,-36.99,RON,28-07-2024,APPLE
4,22-07-2024,Plata OP inter - canal electronic;/ROC/./RFB/2...,"-1,301.00",RON,22-07-2024,BUGETUL GENERAL CONSOLIDAT

In [8]:

# Assuming filtered_df is already loaded with your data

# Convert 'Payment Date' to datetime type ensuring all entries are checked and properly interpreted
filtered_df['Payment Date'] = pd.to_datetime(filtered_df['Payment Date'], errors='coerce', dayfirst=True)

# Convert 'Data tranzactie' to datetime type as well
filtered_df['Data tranzactie'] = pd.to_datetime(filtered_df['Data tranzactie'], errors='coerce', dayfirst=True)

# If you need to display dates in 'DD-MM-YYYY' format, convert datetime objects to strings in the desired format
filtered_df['Formatted Payment Date'] = filtered_df['Payment Date'].dt.strftime('%d-%m-%Y')
filtered_df['Formatted Data Tranzactie'] = filtered_df['Data tranzactie'].dt.strftime('%d-%m-%Y')

# Sort the DataFrame by 'Payment Date'
filtered_df = filtered_df.sort_values(by='Payment Date', ascending=True)

# Now, you can drop the old date columns if they are no longer needed, or keep them as is
# filtered_df.drop(columns=['Payment Date', 'Data tranzactie'], inplace=True)

# Optionally, reorder columns to include the formatted date columns
new_column_order = ['Formatted Payment Date', 'Merchant', 'Descriere', 'Debit', 'Currency']
filtered_df = filtered_df[new_column_order]

filtered_df.head()

,Formatted Payment Date,Merchant,Descriere,Debit,Currency
64,04-07-2024,Namur,Plata la POS non-BT cu card MASTERCARD;EPOS 04...,-45.09,EUR
65,04-07-2024,AMZN,Plata la POS non-BT cu card MASTERCARD;EPOS 04...,-7.82,EUR
67,05-07-2024,142,Plata instant EUR;diurna;;142;mihnea radulescu...,-100.00,EUR
63,05-07-2024,Microsoft,Plata la POS non-BT cu card MASTERCARD;EPOS 05...,-15.40,EUR
6,05-07-2024,APPLE,Plata la POS non-BT cu card VISA;EPOS 05/07/20...,-49.99,RON

In [9]:
filtered_df = filtered_df.rename(
    columns={
        "Formatted Payment Date": "Payment Date",
        "Merchant": "Merchant",
        "Descriere": "Description",
        "Debit": "Debit",
        "Fee Currency": "Currency",
    }
)

filtered_df['Payment Date'] = pd.to_datetime(filtered_df['Payment Date'], format='%d-%m-%Y', errors='coerce')

filtered_df["Account"]="BT Business"

filtered_df

,Payment Date,Merchant,Description,Debit,Currency,Account
64,2024-07-04,Namur,Plata la POS non-BT cu card MASTERCARD;EPOS 04...,-45.09,EUR,BT Business
65,2024-07-04,AMZN,Plata la POS non-BT cu card MASTERCARD;EPOS 04...,-7.82,EUR,BT Business
67,2024-07-05,142,Plata instant EUR;diurna;;142;mihnea radulescu...,-100.00,EUR,BT Business
63,2024-07-05,Microsoft,Plata la POS non-BT cu card MASTERCARD;EPOS 05...,-15.40,EUR,BT Business
6,2024-07-05,APPLE,Plata la POS non-BT cu card VISA;EPOS 05/07/20...,-49.99,RON,BT Business
58,2024-07-05,DELHAIZE,Plata la POS non-BT cu card MASTERCARD;POS 05/...,-66.28,EUR,BT Business
57,2024-07-05,Q8,Plata la POS non-BT cu card MASTERCARD;POS 05/...,-17.49,EUR,BT Business
60,2024-07-06,1,Plata instant EUR;Diurna;;1;mihnea radulescu;L...,-50.00,EUR,BT Business
56,2024-07-06,Q8,Plata la POS non-BT cu card MASTERCARD;POS 06/...,-45.03,EUR,BT Business
53,2024-07-08,LINKEDIN,Plata la POS non-BT cu card MASTERCARD;EPOS 08...,-33.05,EUR,BT Business
50,2024-07-10,Amazon,Plata la POS non-BT cu card MASTERCARD;EPOS 10...,-12.27,EUR,BT Business
49,2024-07-12,Amazon,Plata la POS non-BT cu card MASTERCARD;EPOS 12...,-11.07,EUR,BT Business
46,2024-07-15,NESPRESSO,Plata la POS non-BT cu card MASTERCARD;EPOS 15...,-39.80,EUR,BT Business
45,2024-07-16,Krefel,Plata la POS non-BT cu card MASTERCARD;POS 16/...,-15.00,EUR,BT Business
44,2024-07-17,AMZN,Plata la POS non-BT cu card MASTERCARD;EPOS 17...,-14.91,EUR,BT Business
43,2024-07-17,Q8,Plata la POS non-BT cu card MASTERCARD;POS 17/...,-30.02,EUR,BT Business
40,2024-07-18,AMZN,Plata la POS non-BT cu card MASTERCARD;EPOS 18...,-42.00,EUR,BT Business
42,2024-07-20,JAMBES,Retragere de numerar de la ATM non-BT cu card ...,-20.00,EUR,BT Business
32,2024-07-21,INTERMARCHE,Plata la POS non-BT cu card MASTERCARD;POS 21/...,-40.62,EUR,BT Business
4,2024-07-22,BUGETUL GENERAL CONSOLIDAT,Plata OP inter - canal electronic;/ROC/./RFB/2...,"-1,301.00",RON,BT Business
24,2024-07-23,UBER,Plata la POS non-BT cu card MASTERCARD;EPOS 23...,-66.95,EUR,BT Business
25,2024-07-23,AMZN,Plata la POS non-BT cu card MASTERCARD;EPOS 23...,-38.55,EUR,BT Business
27,2024-07-24,bol.com,Plata SEPA - Echannel;3911356656391;154;bol.co...,-2.99,EUR,BT Business
29,2024-07-24,bol.com,Plata SEPA - Echannel;3911356656389;152;bol.co...,-17.98,EUR,BT Business
21,2024-07-24,DELHAIZE,Plata la POS non-BT cu card MASTERCARD;POS 24/...,-73.00,EUR,BT Business
31,2024-07-24,bol.com,Plata SEPA - Echannel;3911319447674;151;bol.co...,-158.79,EUR,BT Business
20,2024-07-27,TRYFON AEVKE,Plata SEPA - Echannel;Booking 44129781 RADULES...,"-1,945.00",EUR,BT Business
3,2024-07-28,APPLE,Plata la POS non-BT cu card VISA;EPOS 28/07/20...,-36.99,RON,BT Business
15,2024-07-29,Q8,Plata la POS non-BT cu card MASTERCARD;POS 29/...,-13.91,EUR,BT Business
16,2024-07-30,DELHAIZE,Plata la POS non-BT cu card MASTERCARD;POS 30/...,-67.92,EUR,BT Business
1,2024-07-30,PPC,Plata la POS non-BT cu card VISA;EPOS 30/07/20...,"-1,043.83",RON,BT Business
14,2024-07-31,AMZN,Plata la POS non-BT cu card MASTERCARD;EPOS 31...,-20.29,EUR,BT Business
13,2024-08-01,GOOGLE,Plata la POS non-BT cu card MASTERCARD;EPOS 01...,-13.80,EUR,BT Business
2,2024-08-01,NaN,Pachet IZI;Nelimitat in reteaua BT;REF: E41IZ5...,-29.00,RON,BT Business
12,2024-08-02,NESPRESSO,Plata la POS non-BT cu card MASTERCARD;EPOS 02...,-21.90,EUR,BT Business
11,2024-08-03,DELHAIZE,Plata la POS non-BT cu card MASTERCARD;POS 03/...,-46.49,EUR,BT Business
10,2024-08-03,Boulangerie,Plata la POS non-BT cu card MASTERCARD;POS 03/...,-9.15,EUR,BT Business
0,2024-08-05,APPLE,Plata la POS non-BT cu card VISA;EPOS 05/08/20...,-49.99,RON,BT Business
7,2024-08-06,DELHAIZE,Plata la POS non-BT cu card MASTERCARD;POS 06/...,-92.18,EUR,BT Business
9,2024-08-07,153,Plata instant EUR;diurna;;153;mihnea radulescu...,-550.00,EUR,BT Business

In [11]:
filtered_df.to_csv("/home/mihnearad/Development/BankingInfo-Parse-Script/.data/filtered/filtered_bt.csv", index=False)